const actors = [
     {
          "adult": false,
          "also_known_as": [
               "Selena Marie Gomez",
               "셀레나 고메즈",
               "Σελίνα Γκόμεζ",
               "Selena Gomezová",
               "Σελίνα Μαρί Γκόμεζ",
               "赛琳娜·戈麦斯"
          ],
          "biography": "Selena Marie Gomez (/səˈliːnə ˈɡoʊmɛz/ sə-LEE-nə GOH-mez; born July 22, 1992) is an American singer, actress, and producer. She has been regarded as a \"triple threat\". Born and raised in Texas, Gomez began her acting career on the children's television series Barney & Friends (2002–2004). In her teenage years, she rose to prominence for her lead role as Alex Russo in the Disney Channel television series Wizards of Waverly Place (2007–2012).\n\nAlongside her television career, Gomez appeared in the films Another Cinderella Story (2008), Princess Protection Program (2009), Wizards of Waverly Place: The Movie (2009), Ramona and Beezus (2010), Monte Carlo (2011), Spring Breakers (2012), Getaway (2013), The Fundamentals of Caring (2016), The Dead Don't Die (2019), and A Rainy Day in New York (2019). She voiced the character Mavis in the Hotel Transylvania film franchise (2012–2022). Gomez executive produced the Netflix television series 13 Reasons Why (2017–2020) and Living Undocumented (2019) through her production company, July Moonhead Productions. She also executive produces and stars in the HBO Max cooking series Selena + Chef and the Hulu mystery-comedy series Only Murders in the Building. The latter earned Gomez critical praise, and a nomination for Best Actress in a Comedy series at the Critics' Choice Television Awards.\n\nGomez released three albums with her former band, Selena Gomez & the Scene, all of which reached the top ten of the US Billboard 200 and were certified gold by the Recording Industry Association of America: Kiss & Tell (2009), A Year Without Rain (2010), and When the Sun Goes Down (2011). Additionally, Gomez's three solo studio albums—Stars Dance (2013), Revival (2015), and Rare (2020)—each debuted atop the Billboard 200. She also released the Spanish-language EP Revelación (2021), for which she received a nomination for the Grammy Award for Best Latin Pop Album. A number of Gomez's singles have charted inside the top ten of the US Billboard Hot 100, including \"Come & Get It\", \"The Heart Wants What It Wants\", \"Good for You\", \"Same Old Love\", \"Hands to Myself\", \"We Don't Talk Anymore\", \"It Ain't Me\", and her first number-one song \"Lose You to Love Me\". Her music is known for its hushed vocal styles.\n\nAs of 2017, Gomez has sold over seven million albums and 22 million singles worldwide, according to Billboard. She has received various accolades and was named Billboard's Woman of the Year in 2017. Time magazine named her one of the 100 most influential people in the world in 2020. She has a large following on social media and is the most followed musician and actress on Instagram. Gomez's other ventures include makeup, clothing, handbag and fragrance lines. She has worked with many charitable organizations and served as a UNICEF ambassador since age 17.\n\nDescription above from the Wikipedia article Selena Gomez, licensed under CC-BY-SA, full list of contributors on Wikipedia.",
          "birthday": "1992-07-22",
          "deathday": null,
          "gender": 1,
          "homepage": "http://www.selenagomez.com",
          "id": 77948,
          "imdb_id": "nm1411125",
          "known_for_department": "Acting",
          "name": "Selena Gomez",
          "place_of_birth": "Grand Prairie, Texas, USA ",
          "popularity": 8.545,
          "profile_path": "/n20WIggAI2Mmwa4OAkPnCSrCx1j.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "The Rock",
               "Rocky Maivia",
               "The Brahma Bull",
               "The Corporate Champion",
               "Двейн Джонсон",
               "Скеля",
               "Big Bull",
               "드웨인 존슨",
               "Flex Kavana",
               "Dwayne Douglas Johnson",
               "Ντουέιν Ντάγκλας Τζόνσον",
               "Ντουέιν Τζόνσον",
               "道恩·强森",
               "La Roca",
               "Dwayne ‘The Rock’ Johnson",
               "دوين جونسون",
               "الصخرة",
               "巨石強森",
               "ഡ്വെയ്ൻ ജോൺസൺ",
               "The Peoples Champion",
               "The Great One",
               "Скала",
               "דווין ג'ונסון"
          ],
          "biography": "An American and Canadian actor, producer and semi-retired professional wrestler, signed with WWE.  Johnson is half-Black and half-Samoan. His father, Rocky Johnson, is a Black Canadian, from Nova Scotia, and part of the first Black tag team champions in WWE history back when it was known as the WWF along with Tony Atlas. His mother is Samoan and the daughter of Peter Maivia, who was also a pro wrestler. Maivia's wife, Lia Maivia, was one of wrestling's few female promoters, taking over Polynesian Pacific Pro Wrestling after her husband's death in 1982, until 1988. Through his mother, he is considered a non-blood relative of the Anoa'i wrestling family. On March 29, 2008, The Rock inducted his father and his grandfather into the WWE Hall of Fame.\n\nAs of 2014, Johnson has a home in Southwest Ranches, Florida as well as Los Angeles, California. He also owns a farm in Virginia. In 2009, Johnson gained citizenship in Canada in honor of his father's background. Though Johnson was previously registered as a Republican, he voted for Barack Obama in the 2008 and 2012 United States presidential elections and is now an independent voter. He stated he did not vote in the 2016 U.S. election.\n\nIn recognition of his service to the Samoan people, and because he is a descendant of Samoan chiefs, Johnson had the noble title of Seiuli bestowed upon him by Malietoa Tanumafili II during his visit there in July 2004. He received a partial Samoan pe'a tattoo on his left side in 2003,and, in 2017, had the small \"Brahma bull\" tattoo on his right arm covered with a larger half-sleeve tattoo of a bull's skull.\n\nJohnson married Dany Garcia on May 3, 1997. Their only child together, a daughter named Simone, was born in August 2001. On June 1, 2007, they announced they were splitting up amicably. Johnson then began dating Lauren Hashian, daughter of Boston drummer Sib Hashian. They first met in 2006 while Johnson was filming The Game Plan. Their first child together, a daughter, was born in December 2015. Their second child, another daughter, was born in April 2018.\n\nJohnson attended the 2000 Democratic National Convention as part of WWE's non-partisan \"Smackdown Your Vote\" campaign, which aimed to influence young people to vote. He also had a speaking role at the 2000 Republican National Convention that same year.\n\nIn 2006, Johnson founded the Dwayne Johnson Rock Foundation, a charity working with at-risk and terminally ill children. On October 2, 2007, he and his ex-wife donated $1 million to the University of Miami to support the renovation of its football facilities; it was noted as the largest donation ever given to the university's athletics department by former students. The University of Miami renamed the Hurricanes' locker room in Johnson's honor. In 2015, Johnson donated $1,500 to a GoFundMe to pay for an abandoned dog's surgery. In 2017, he donated $25,000 to Hurricane Harvey relief efforts. In 2018, Johnson donated a gym to a military base in Oahu, Hawaii. After the 2018 Hawaii floods, he worked with Malama Kauai, a nonprofit organization, to help repair damages caused by the floods.",
          "birthday": "1972-05-02",
          "deathday": null,
          "gender": 2,
          "homepage": "https://www.wwe.com/superstars/the-rock",
          "id": 18918,
          "imdb_id": "nm0425005",
          "known_for_department": "Acting",
          "name": "Dwayne Johnson",
          "place_of_birth": "Hayward, California, USA",
          "popularity": 51.467,
          "profile_path": "/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "Анджелина Джоли",
               "Angelina Jolie-Pitt",
               "安吉丽娜·朱莉",
               "アンジェリーナ・ジョリー",
               "แอนเจลีนา โจลี",
               "안젤리나 졸리",
               "أنجلينا جولي",
               "Анджеліна Джолі",
               "Angelina Jolie Voight",
               "ანჯელინა ჯოლი",
               "Αντζελίνα Τζολί",
               "Angelina Voight",
               "安祖蓮娜·祖莉",
               "എയ്‌ഞ്ചലിന ജോളി "
          ],
          "biography": "Angelina Jolie is an American actress. She has received an Academy Award, two Screen Actors Guild Awards, and three Golden Globe Awards. Jolie has promoted humanitarian causes throughout the world, and is noted for her work with refugees as a Goodwill Ambassador for the United Nations High Commissioner for Refugees (UNHCR). She has been cited as one of the world's most beautiful women and her off-screen life is widely reported.\n\nThough she made her screen debut as a child alongside her father Jon Voight in the 1982 film Lookin' to Get Out, Jolie's acting career began in earnest a decade later with the low-budget production Cyborg 2 (1993). Her first leading role in a major film was in Hackers (1995). She starred in the critically acclaimed biographical films George Wallace (1997) and Gia (1998), and won an Academy Award for Best Supporting Actress for her performance in the drama Girl, Interrupted (1999). Jolie achieved wider fame after her portrayal of video game heroine Lara Croft in Lara Croft: Tomb Raider (2001), and since then has established herself as one of the best-known and highest-paid actresses in Hollywood. She has had her biggest commercial successes with the action-comedy Mr. & Mrs. Smith (2005) and the animated film Kung Fu Panda (2008).\n\nDivorced from actors Jonny Lee Miller and Billy Bob Thornton, Jolie currently lives with actor Brad Pitt, in a relationship that has attracted worldwide media attention. Jolie and Pitt have three adopted children, Maddox, Pax, and Zahara, as well as three biological children, Shiloh, Knox, and Vivienne.",
          "birthday": "1975-06-04",
          "deathday": null,
          "gender": 1,
          "homepage": "https://www.unhcr.org/pages/49c3646c56.html",
          "id": 11701,
          "imdb_id": "nm0001401",
          "known_for_department": "Acting",
          "name": "Angelina Jolie",
          "place_of_birth": "Los Angeles, California, USA ",
          "popularity": 17.116,
          "profile_path": "/k3W1XXddDOH2zibPkNotIh5amHo.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "برد پیت",
               "Бред Пітт",
               "Брэд Питт",
               "畢·彼特",
               "ブラッド・ピット",
               "브래드 피트",
               "براد بيت",
               "แบรด พิตต์",
               "William Bradley \"Brad\" Pitt",
               "William Bradley Pitt",
               "Μπραντ Πιτ",
               "布拉德·皮特",
               "Breds Pits",
               "ബ്രാഡ് പിറ്റ് ",
               "ბრედ პიტი"
          ],
          "biography": "William Bradley Pitt (born December 18, 1963) is an American actor and film producer. He is the recipient of various accolades, including an Academy Award, a British Academy Film Award, and two Golden Globe Awards for his acting, in addition to a second Academy Award, a second British Academy Film Award, a third Golden Globe Award, and a Primetime Emmy Award as a producer under his production company, Plan B Entertainment.\n\nPitt first gained recognition as a cowboy hitchhiker in the road film Thelma & Louise (1991). His first leading roles in big-budget productions came with the drama films A River Runs Through It (1992) and Legends of the Fall (1994), and the horror film Interview with the Vampire (1994). He gave critically acclaimed performances in the crime thriller Seven (1995) and the science fiction film 12 Monkeys (1995), the latter earning him a Golden Globe Award for Best Supporting Actor and an Academy Award nomination.\n\nPitt starred in Fight Club (1999) and the heist film Ocean's Eleven (2001), as well as its sequels, Ocean's Twelve (2004) and Ocean's Thirteen (2007). His greatest commercial successes have been Ocean's Eleven (2001), Troy (2004), Mr. & Mrs. Smith (2005), World War Z (2013), and Once Upon a Time in Hollywood (2019), for which he won a second Golden Globe Award and the Academy Award for Best Supporting Actor. Pitt's other Academy Award nominated performances were in The Curious Case of Benjamin Button (2008) and Moneyball (2011). He produced The Departed (2006) and 12 Years a Slave (2013), both of which won the Academy Award for Best Picture, and also The Tree of Life (2011), Moneyball (2011) and The Big Short (2015), all of which were nominated for Best Picture. Pitt is the second actor to have won Academy Awards for both Best Supporting Actor and Best Picture.",
          "birthday": "1963-12-18",
          "deathday": null,
          "gender": 2,
          "homepage": null,
          "id": 287,
          "imdb_id": "nm0000093",
          "known_for_department": "Acting",
          "name": "Brad Pitt",
          "place_of_birth": "Shawnee, Oklahoma, USA",
          "popularity": 34.777,
          "profile_path": "/oAvLuGuTaNcjY3R5huBQdfrZN6j.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "Emma Charlotte Duerre Watson",
               "Эмма Уотсон",
               "엠마 왓슨",
               "Emma Vatsone",
               "艾玛·沃森",
               "艾玛·夏洛特·杜尔热·沃森",
               "Έμμα Σάρλοτ Ντουέρ Γουάτσον",
               "Έμμα Γουάτσον",
               "إيما واتسون",
               "אמה ווטסון",
               "אמה שרלוט דיורי ווטסון"
          ],
          "biography": "Emma Charlotte Duerre Watson (born 15 April 1990) is an English actress and activist. She has gained recognition for her roles in both blockbusters and independent films, as well as her women's rights work. Watson has been ranked among the world's highest-paid actresses by Forbes and Vanity Fair, and was named one of the 100 most influential people in the world by Time magazine in 2015.\n\nWatson attended the Dragon School and trained in acting at the Oxford branch of Stagecoach Theatre Arts. As a child, she rose to stardom after landing her first professional acting role as Hermione Granger in the Harry Potter film series, having acted only in school plays previously. Watson also starred in the 2007 television adaptation of the novel Ballet Shoes and lent her voice to The Tale of Despereaux (2008). After the final Harry Potter film, she took on a supporting role in My Week with Marilyn (2011), before starring as Sam, a flirtatious, free-spirited student in The Perks of Being a Wallflower (2012) to critical success.\n\nFurther acclaim came from portraying Alexis Neiers in Sofia Coppola's The Bling Ring (2013) and the titular character's adoptive daughter in the biblical epic Noah. That same year, Watson was honoured by the British Academy of Film and Television Arts, winning British Artist of the Year. She also starred as Belle in the musical romantic fantasy Beauty and the Beast (2017), which ranks among the highest-grossing films of all time, and Meg March in the coming-of-age drama Little Women (2019).\n\nFrom 2011 to 2014, Watson split her time between working on films and continuing her education, graduating from Brown University with a bachelor's degree in English literature in May 2014. That year, she was appointed a UN Women Goodwill Ambassador and helped launch the UN Women campaign HeForShe, which advocates for gender equality. In 2018, she helped launch Time's Up UK as a founding member. Watson was appointed to a G7 advisory body for women's rights in 2019, consulting with leaders on foreign policy. Her modelling work has included campaigns for Burberry and Lancôme. She also lent her name to a clothing line for the sustainable brand People Tree. In 2020, she joined the board of directors of Kering, a luxury brand group, in her capacity as an advocate for sustainable fashion.",
          "birthday": "1990-04-15",
          "deathday": null,
          "gender": 1,
          "homepage": null,
          "id": 10990,
          "imdb_id": "nm0914612",
          "known_for_department": "Acting",
          "name": "Emma Watson",
          "place_of_birth": "Paris, France",
          "popularity": 25.487,
          "profile_path": "/tvPPRGzAzdQFhlKzLbMO1EpuTJI.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "Jennifer Shrader Lawrence",
               "제니퍼 로렌스",
               "ジェニファー・ローレンス",
               "جينيفر لورنس",
               "เจนนิเฟอร์ ลอว์เรนซ์",
               "珍妮佛·勞倫斯",
               "Џенифер Лоренс",
               "ჯენიფერ ლოურენსი",
               "Τζένιφερ Σρέιντερ Λόρενς",
               "Τζένιφερ Λόρενς",
               "جنیفر لارنیس",
               "Дженніфер Лоренс",
               "Дженнифер Лоуренс"
          ],
          "biography": "Jennifer Shrader Lawrence (born August 15, 1990) is an American actress. The world's highest-paid actress in 2015 and 2016, her films have grossed over $6 billion worldwide to date. She appeared in Time's 100 most influential people in the world list in 2013 and the Forbes Celebrity 100 list from 2013 to 2016.\n\nDuring childhood, Lawrence performed in church plays and school musicals. At 14, she was spotted by a talent scout while vacationing in New York City with her family. She moved to Los Angeles and began her acting career in guest roles on television. Her first major role was that of a main cast member on the sitcom The Bill Engvall Show (2007–2009). She made her film debut in a supporting role in the drama Garden Party (2008), and had her breakthrough playing Ree Dolly, a poverty-stricken teenage girl, in the coming-of-age independent mystery drama Winter's Bone (2010). Lawrence's career progressed with starring roles as the mutant Mystique in the X-Men film series (2011–2019) and Katniss Everdeen in The Hunger Games film series (2012–2015). The latter made her the highest-grossing action heroine of all time.\n\nLawrence has received a number of accolades for various films, including her three collaborations with filmmaker David O. Russell. Her performance as a young widow with an unnamed mental disorder in the romance film Silver Linings Playbook (2012) won her the Academy Award for Best Actress, making her the second-youngest Best Actress winner at 22. She won the BAFTA Award for Best Actress in a Supporting Role for playing an unpredictable wife in the black comedy American Hustle (2013). Lawrence also received Golden Globe Awards for both of these films, and for her portrayal of businesswoman Joy Mangano in the biopic Joy (2015). A series of negatively reviewed films, including Passengers (2016) and Red Sparrow (2018), and the subsequent media scrutiny of her choices of roles led to a small break from acting. She returned in 2021 with the satirical black comedy Don't Look Up.",
          "birthday": "1990-08-15",
          "deathday": null,
          "gender": 1,
          "homepage": "http://jenniferlawrencefoundation.com",
          "id": 72129,
          "imdb_id": "nm2225369",
          "known_for_department": "Acting",
          "name": "Jennifer Lawrence",
          "place_of_birth": "Indian Hills, Kentucky, USA",
          "popularity": 33.516,
          "profile_path": "/nApY80UBr58POBMKKxei3kHZR8D.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "Уилл Смит",
               "Вілл Сміт",
               "The Fresh Prince",
               "Willard Smith",
               "ويل سميث",
               "윌 스미스",
               "วิลล์ สมิธ",
               "威爾·史密斯",
               "וויל סמית",
               "Γουίλ Σμιθ",
               "Willard Christopher \"Will\" Smith, Jr.",
               "Willard Christopher Smith, Jr.",
               "威尔·史密斯",
               "വിൽ സ്മിത്ത് ",
               " Γουίλαρντ Κάρολ Σμιθ"
          ],
          "biography": "Willard Christopher \"Will\" Smith, Jr. (born September 25, 1968) is an American actor, film producer and pop rapper. He has enjoyed success in music, television and film. In April 2007, Newsweek called him the most powerful actor on the planet. Smith has been nominated for four Golden Globe Awards, two Academy Awards, and has won multiple Grammy Awards.\n\nIn the late 1980s, Smith achieved modest fame as a rapper under the name The Fresh Prince. In 1990, his popularity increased dramatically when he starred in the popular television series The Fresh Prince of Bel-Air. The show ran for nearly six years (1990–1996) on NBC and has been syndicated consistently on various networks since then.\n\nIn the mid-1990s, Smith transitioned from television to film, and ultimately starred in numerous blockbuster films that received broad box office success. In fact, he is the only actor in history to have eight consecutive films gross over $100 million in the domestic box office as well as being the only actor to have eight consecutive films in which he starred open at the #1 spot in the domestic box office tally. Fourteen of the 19 fiction films he has acted in have accumulated worldwide gross earnings of over $100 million, and 4 of them took in over $500 million in global box office receipts. His most financially successful films have been Bad Boys, Bad Boys II, Independence Day, Men in Black, Men in Black II, I, Robot, The Pursuit of Happyness, I Am Legend, Hancock, Wild Wild West, Enemy of the State, Shark Tale, Hitch, and Seven Pounds. He also earned critical praise for his performances in Six Degrees of Separation, Ali, and The Pursuit of Happyness, receiving Best Actor Oscar nominations for the latter two.",
          "birthday": "1968-09-25",
          "deathday": null,
          "gender": 2,
          "homepage": "http://www.willsmith.com",
          "id": 2888,
          "imdb_id": "nm0000226",
          "known_for_department": "Acting",
          "name": "Will Smith",
          "place_of_birth": "Philadelphia, Pennsylvania, USA ",
          "popularity": 24.591,
          "profile_path": "/6a6cl4ZNufJzrx5HZKWPU1BjjRF.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "Киллиан Мерфи",
               "คิลเลียน เมอร์ฟี",
               "キリアン・マーフィー",
               "基利安·墨菲",
               "킬리언 머피",
               "كيليان مورفي",
               "希里安·墨菲"
          ],
          "biography": "Cillian Murphy is an Irish film and theatre actor. He is often noted by critics for his chameleonic performances in diverse roles and distinctive blue eyes. A native of Cork, Murphy began his performing career as a rock musician. After turning down a record deal, he made his professional acting debut in the play Disco Pigs in 1996. He went on to star in Irish and UK film and stage productions throughout the late 1990s and early 2000s, first coming to international attention in 2003 as the hero in the post-apocalyptic film 28 Days Later.\n\nMurphy is best known for his work with director Christopher Nolan, where he appeared as the villain Jonathan Crane/Scarecrow in all three films in the Dark Knight trilogy. Murphy has also worked with Nolan on Inception and Dunkirk. In 2013, Murphy started working on a TV show for BBC titled “Peaky Blinders” as the show’s lead role, Thomas Shelby. The show is still airing as of 2020 with five highly critically acclaimed seasons under its belt A resident of London since 2001, Murphy often works in or near the city and has expressed no desire to move to Hollywood. Uncomfortable on the celebrity circuit, he customarily gives interviews about his work, but does not appear on television talk shows or discuss details of his private life with the press.\n\nBorn in Douglas and raised in Ballintemple, two suburbs of Cork, Cillian Murphy is the eldest of four children. His father, Brendan, works for the Irish Department of Education and his mother is a French teacher. Not only are his parents educators, but his aunts and uncles are also teachers, as was his grandfather. Musicianship also runs in the family, and Murphy started playing music and writing songs at age ten. In mid-2004, Murphy married his long-time live-in girlfriend, Yvonne McGuinness, an artist whom he met in 1996 at one of his rock band's shows. The couple live in northwest London with their two sons Malachy (born in 2005) and Aaron (born in 2007).\n\nMurphy is known for being reluctant to speak about his personal life. He frequently gives interviews about his work but did not appear on a single live TV chat show, where actors customarily share information about their private lives, until 2010, when he was a guest on The Late Late Show on Ireland's RTÉ to promote Perrier's Bounty. He does not have a stylist or a personal publicist, travels without an entourage, and often attends premieres alone. Shy and private, Murphy professes a lack of interest in the celebrity scene, finding the red carpet experience \"a challenge... and not one I want to overcome.\" He intentionally practices a lifestyle that will not interest the tabloids: \"I haven't created any controversy, I don't sleep around, I don't go and fall down drunk.\" Murphy is friends with fellow Irish actors Colin Farrell and Liam Neeson, looking up to the latter like a \"surrogate movie dad\". But primarily, Murphy's close friendships are those he made before becoming a star.",
          "birthday": "1976-05-25",
          "deathday": null,
          "gender": 2,
          "homepage": null,
          "id": 2037,
          "imdb_id": "nm0614165",
          "known_for_department": "Acting",
          "name": "Cillian Murphy",
          "place_of_birth": "Douglas, Cork, Ireland",
          "popularity": 85.304,
          "profile_path": "/i8dOTC0w6V274ev5iAAvo4Ahhpr.jpg"
     },
     {
          "adult": false,
          "also_known_as": [
               "גל גדות",
               "Галь Гадот",
               "盖尔·加朵",
               "กัล กาด็อต",
               "ガル・ガドット",
               "غال غادوت",
               "갤 가돗",
               "Γκαλ Γκαντότ-Βαρσάνο",
               "Γκαλ Γκαντότ",
               "蓋兒·加朵",
               "Ґаль Ґадот",
               "Гал Гадот"
          ],
          "biography": "Gal Gadot (born: April 30, 1985) is an Israeli actress and model. She was born in Rosh Ha'ayin, Israel, to an Ashkenazi Jewish family (from Poland, Austria, Germany, and Czechoslovakia). She served in the IDF for two years, and won the Miss Israel title in 2004.\n\nGal began modeling in the late 2000s, and made her film debut in the fourth film of the Fast and Furious franchise, Fast & Furious (2009), as Gisele, an associate of the film's lead villain. Her role was expanded in the sequels Fast Five (2011) and Fast & Furious 6 (2013), in which her character was romantically linked to Han Seoul-Oh (Sung Kang). In the films, Gal performed her own stunts. She also appeared in the 2010 films Date Night (2010) and Knight and Day (2010). In early December 2013, Gal was cast as Wonder Woman in the DC Extended Universe.\n\nGal is a motorcycle enthusiast, and owns a black 2006 Ducati Monster-S2R. She has been married to Yaron Versano since September 28, 2008. They have one child.",
          "birthday": "1985-04-30",
          "deathday": null,
          "gender": 1,
          "homepage": "http://www.galgadot.com",
          "id": 90633,
          "imdb_id": "nm2933757",
          "known_for_department": "Acting",
          "name": "Gal Gadot",
          "place_of_birth": "Rosh Ha'ayin, Israel",
          "popularity": 40.077,
          "profile_path": "/plLfB60M5cJrnog8KvAKhI4UJuk.jpg"
     }
]

export default actors;